# pandoc --defaults _codebraid_preview.yml --pdf-engine weasyprint -o report.pdf
input-files:
- introduction.md
- project-planning.md
- meeting-agenda.md
- market-research.md
- user-requirements.md


# adds preface.md before the table of contents, and removes the headings of this file from the index
# include-before-body: header.html

table-of-contents: true
toc-depth: 3
#
variables:
  toc-title: "Table of Contents"

